[env:seeed_xiao_esp32c6]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.20/platform-espressif32.zip
platform_packages =
    platformio/tool-esptoolpy @ ~2.41100.0
board = seeed_xiao_esp32c6
framework = arduino
monitor_speed = 115200
lib_deps =
    olikraus/U8g2@^2.35.7
